### ISSUE TITLE
Unable to build jar: Cannot convert the provided notation to a File or URI: java.io.BufferedWriter@

### ISSUE THREAD

**Issue by claudiga** [rholder/gradle-one-jar#34]
I am trying to build a jar, so i followed the instructions but every-time i run the task i get this error. I'm i missing something in the build.gradle file?

Execution failed for task ':awesomeFunJar'.
> Cannot convert the provided notation to a File or URI: java.io.BufferedWriter@48e04250.
  The following types/formats are supported:
    - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
    - A String or CharSequence URI, for example 'file:/usr/include'.
    - A File instance.
    - A Path instance.
    - A Directory instance.
    - A RegularFile instance.
    - A URI or URL instance.

_______________________________________________________________________________________

My build.gradle is:

```
apply plugin: 'gradle-one-jar'
apply plugin: 'java'


buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.github.rholder:gradle-one-jar:1.0.4'
    }
}


task awesomeFunJar(type: OneJar) {
    mainClass = 'com.practice.Application'
}

repositories {
  
        mavenCentral()
}

dependencies {
    
}
```

**Comment by haribachala** [comment]
I am also facing the same issue, with latest gradle 4.2.

**Comment by rherrmann7** [comment]
Ditto...  I'm going to give shadow a try instead.... https://github.com/johnrengelman/shadow

**Comment by claudiga** [comment]
I just use the java plugin it works pretty well

**Comment by mnlipp** [comment]
Confirmed as issue for gradle 4.8.1.

**Comment by nros** [comment]
the missing stack trace is:
```
Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to a File or URI: java.io.BufferedWriter@7107255.
The following types/formats are supported:
  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
  - A String or CharSequence URI, for example 'file:/usr/include'.
  - A File instance.
  - A Path instance.
  - A Directory instance.
  - A RegularFile instance.
  - A URI or URL instance.
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:56)
        at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:117)
        at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:69)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:85)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:67)
        at org.gradle.api.java.archives.internal.DefaultManifest.writeTo(DefaultManifest.java:215)
        at org.gradle.api.java.archives.Manifest$writeTo.call(Unknown Source)
        at com.github.rholder.gradle.task.OneJar$_writeOneJarManifestFile_closure4.doCall(OneJar.groovy:187)
        at com.github.rholder.gradle.task.OneJar.writeOneJarManifestFile(OneJar.groovy:182)
        at com.github.rholder.gradle.task.OneJar$writeOneJarManifestFile.callCurrent(Unknown Source)
        at com.github.rholder.gradle.task.OneJar.buildOneJar(OneJar.groovy:164)
        at com.github.rholder.gradle.task.OneJar$_closure1.doCall(OneJar.groovy:113)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:732)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:705)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 29 more

```

**Comment by nros** [comment]
this commit in a fork fixes this issue:
https://github.com/bryanxtong/gradle-one-jar/commit/ba3b7cbd94f2e3b809f19614e8a9d6b8c29ef67c

already in pull request https://github.com/rholder/gradle-one-jar/pull/32

**Comment by nros** [comment]
To include your own local copy of the fixed plugin into your gradle build, see here:
https://stackoverflow.com/questions/35302414/adding-local-plugin-to-a-gradle-project#answer-35472676

```Groovy
buildscript{
    repositories{
        ...
    }

    dependencies{
        classpath files('relative/path/to/plugin.jar')
    }
}

apply plugin: fully.qualified.package.PluginClassName
```

**Comment by pskowronek** [comment]
Any hope for new release including the provided pull request #32? It is like 3 months already and still no official release...

**Comment by danailKondov** [comment]
Same error, fix it already plz

**Comment by herbertpimentel** [comment]
theres any known workaround for this ?

**Comment by nsoft** [comment]
I've forked one-jar into https://github.com/nsoft/uno-jar and provided a gradle task. Let me know if something isn't working.

**Comment by nreckle** [comment]
I have the same issue.
